language: python
python:
- '3.6'
- '3.7'
install:
- pip install numpy
- pip install matplotlib
- pip install flake8
- pip install pytest-cov
script: 
 - pytest ./travelplanner/tests
 - python3 -m doctest ./travelplanner/__init__.py
deploy:
  provider: pypi
  user: ShouyiWang19     # pypi user
  password: Wsy907501712  # pypi password
  on:
    tags: False
    branch: master
    python: 3.7
